import os
import uuid
from fastapi import FastAPI, BackgroundTasks, HTTPException
from fastapi.responses import FileResponse
import yt_dlp

app = FastAPI()

# Aapki YouTube Cookies
YOUTUBE_COOKIES = """# Netscape HTTP Cookie File
# http://curl.haxx.se/rfc/cookie_spec.html
# This file was generated by Cookie-Editor
#HttpOnly_.youtube.com	TRUE	/	TRUE	1806871859	__Secure-3PSID	g.a0007QjfOpQ4yyti4XWsktUqq0sFM8Ak3vq_cUee0iNjFBhso6XoIv68Ka0CqUJUSqfttYCPHgACgYKAV8SARYSFQHGX2MioFVFIdqkLzISOyTl4vSKxhoVAUF8yKr1o5BQfkFMROTQpTppgJuO0076
#HttpOnly_.youtube.com	TRUE	/	TRUE	1803847859	__Secure-1PSIDTS	sidts-CjUBBj1CYv7aOM0opNV9fPjZT5p6KM6sHuccvih64mg4qd1AGK82ktI85CYmTofpPTe34Vkc7xAA
.youtube.com	TRUE	/	TRUE	1772312770	CONSISTENCY	AG2Tqf8wEHdIZqATyft4sESG9iyCro7p6AeRLbCt0E75dvJ_yprVor27IsQcUzoD1zeUBIRCBzZA_7CuLxIHglly6_pQss3IFBAx85Y25Vk9cvCdCCwcs9b9ygEfCFu14N0_K6rF3IgwBYWs99RKcp0yNRKt1IwTAgcx
.youtube.com	TRUE	/	TRUE	1806871859	__Secure-3PAPISID	AdpyKORv1BWZZ-XZ/ASjxoR9eKAIVXbdnL
#HttpOnly_.youtube.com	TRUE	/	TRUE	1803848270	__Secure-3PSIDCC	AKEyXzXyW2QsPS8wmvA7d1-yemwCddXVcVWo5pnkXZ3FzklNMYBDJXFZX0XUfnuEq6bHlvVZWQ
#HttpOnly_.youtube.com	TRUE	/	TRUE	1803847859	__Secure-3PSIDTS	sidts-CjUBBj1CYv7aOM0opNV9fPjZT5p6KM6sHuccvih64mg4qd1AGK82ktI85CYmTofpPTe34Vkc7xAA
#HttpOnly_.youtube.com	TRUE	/	TRUE	1806871859	LOGIN_INFO	AFmmF2swRgIhAPoZ8e2tcnactqZS4Oe0C3Dybh7jBjRDA3rI7pPOwHBEAiEA7nFWvX71EdiKpMHnvbR2yCsRjJTY-Axi-Bv_ei6WJ4o:QUQ3MjNmeWtiTEpiVFhmRWhJY0FWSEh6NVJoVlZYWG9ZMkdOVjJBNUo4cFRtUWhtR09acHl4cDh4VGlTWl9yQ2lwT05PelROeVBvbktWZURBcDBoaEtOQ3hlY2UxVHVqWDBnMUU2WEE4c2V6czBUZkFZaXJxcjRFc2Q4WmdiTllXXy0xeW9qd3ZaXzZvbDU0S185czVVU2ZUOHl2RGkySEZn
.youtube.com	TRUE	/	TRUE	1806872221	PREF	tz=Asia.Calcutta"""

# Startup par automatically cookies.txt file banana
@app.on_event("startup")
async def startup_event():
    with open("cookies.txt", "w") as f:
        f.write(YOUTUBE_COOKIES)

def remove_file(path: str):
    if os.path.exists(path):
        os.remove(path)

@app.get("/{url:path}")
async def download_video(url: str, background_tasks: BackgroundTasks):
    clean_url = url
    
    # URL theek karne ka logic
    if clean_url.startswith("http:/") and not clean_url.startswith("http://"):
        clean_url = clean_url.replace("http:/", "http://", 1)
    elif clean_url.startswith("https:/") and not clean_url.startswith("https://"):
        clean_url = clean_url.replace("https:/", "https://", 1)
        
    if not clean_url.startswith("http"):
        if len(clean_url) == 11 and " " not in clean_url:
            clean_url = f"https://www.youtube.com/watch?v={clean_url}"
        else:
            clean_url = "https://" + clean_url

    file_id = str(uuid.uuid4())
    filepath = f"{file_id}.mp4"
    
    # Yahan saari Settings aur Bypass Tricks lagayi gayi hain
    ydl_opts = {
        'outtmpl': filepath,
        'format': 'best',
        'quiet': True,
        'no_warnings': True,
        'nocheckcertificate': True,
        'cookiefile': 'cookies.txt',  # Aapki Cookies
        'source_address': '0.0.0.0',  # DNS Network Error Fix
        'extractor_args': {'youtube': ['client=android', 'player_client=android']}, # Naya Android Bypass Trick
    }
    
    try:
        # Video Download Start
        with yt_dlp.YoutubeDL(ydl_opts) as ydl:
            info = ydl.extract_info(clean_url, download=True)
            title = info.get('title', 'downloaded_video').replace('/', '_').replace('\\', '_')
            
        background_tasks.add_task(remove_file, filepath)
        
        # Phone me direct download bhejna
        return FileResponse(
            path=filepath, 
            media_type='video/mp4', 
            filename=f"{title}.mp4"
        )
    except Exception as e:
        raise HTTPException(status_code=400, detail=f"Download failed: {str(e)}")
